# Generated by Django 3.0.1 on 2020-09-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminID', models.AutoField(primary_key=True, serialize=False)),
                ('AdminFirstName', models.CharField(max_length=50)),
                ('AdminLastName', models.CharField(max_length=50)),
                ('AdminPassword', models.CharField(max_length=16)),
                ('AdminAddress', models.CharField(max_length=150)),
                ('AdminPhone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('ParentID', models.CharField(max_length=50)),
                ('CategoryName', models.CharField(max_length=50)),
                ('CategoryDescription', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('ConversationID', models.AutoField(primary_key=True, serialize=False)),
                ('Massage', models.CharField(max_length=100)),
                ('IP', models.CharField(max_length=50)),
                ('DateAndTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerFirstName', models.CharField(max_length=50)),
                ('CustomerLastName', models.CharField(max_length=50)),
                ('CustomerEmailAddress', models.EmailField(max_length=50)),
                ('CustomerPassword', models.CharField(max_length=18)),
                ('CustomerAddress', models.CharField(max_length=50)),
                ('CustomerPhone', models.IntegerField()),
                ('CustomerCity', models.CharField(max_length=50)),
                ('CustomerState', models.CharField(max_length=50)),
                ('CustomerPostalCode', models.IntegerField()),
                ('CustomerCountry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Boy',
            fields=[
                ('DeliveryBoyID', models.AutoField(primary_key=True, serialize=False)),
                ('DeliveryBoyFirstName', models.CharField(max_length=50)),
                ('DeliveryBoyLastName', models.CharField(max_length=50)),
                ('DeliveryBoyPassword', models.CharField(max_length=16)),
                ('DeliveryBoyAddress', models.CharField(max_length=150)),
                ('DeliveryBoyPhone', models.IntegerField()),
                ('DeliveryBoyShift', models.CharField(max_length=50)),
                ('DeliveryBoySalary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField()),
                ('OrderStatus', models.CharField(max_length=50)),
                ('OrderComment', models.CharField(max_length=150)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('CartID', models.IntegerField()),
                ('PaymentDate', models.DateField()),
                ('AmountReceived', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierID', models.AutoField(primary_key=True, serialize=False)),
                ('SupplierFirstName', models.CharField(max_length=50)),
                ('SupplierLastName', models.CharField(max_length=50)),
                ('SupplierAddress', models.CharField(max_length=150)),
                ('SupplierPhone', models.IntegerField()),
                ('SupplierCompanyName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category_Attributes',
            fields=[
                ('AttributeID', models.AutoField(primary_key=True, serialize=False)),
                ('AttributeName', models.CharField(max_length=50)),
                ('SubCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('ShoppingCartID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalPrice', models.IntegerField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=60)),
                ('ProductDescription', models.CharField(max_length=150)),
                ('ProductPrice', models.IntegerField()),
                ('Product_image', models.ImageField(upload_to='images')),
                ('SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('OrderDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderNum', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('DeliveryDate', models.DateField()),
                ('CartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Shopping_Cart')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Order')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation_Reply',
            fields=[
                ('ConversationReplyID', models.AutoField(primary_key=True, serialize=False)),
                ('ConversationReply', models.CharField(max_length=50)),
                ('DateAndTime', models.DateField()),
                ('ConversationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Conversation')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Customer'),
        ),
        migrations.CreateModel(
            name='Attributes_Data',
            fields=[
                ('AttributeDataID', models.AutoField(primary_key=True, serialize=False)),
                ('AttributeValue', models.CharField(max_length=150)),
                ('AttributeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Sub_Category_Attributes')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Product')),
            ],
        ),
    ]
