# Generated by Django 3.0.2 on 2020-09-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProductPrice',
            new_name='ProductMaxPrice',
        ),
        migrations.AddField(
            model_name='product',
            name='ProductMinPrice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
